In [49]:
# Imports for scraping and storing as a data frame
import urllib2
import requests
import pandas as pd
import numpy as np

In [50]:
"""
A function that creates a list of all the years to scrape 
from dougstats.com.
"""
def get_years(start=99, stop=17):
    years = []
    end = (start + 1) % 100
    
    print "Filling years:"
    while start != stop:
        interval = time_interval(start, end)
        print interval
        years.append(interval)
        start = end
        end = (end + 1) % 100

    print ""
    return years

"""
Helper function to output the correct time interval
given a start time and and end time.
"""
def time_interval(start, end):
    if start == 99:
        return "99-00"
    elif start == 0:
        return "00-01"
    else:
        s, e = str(start), str(end)
        if len(s) == 1:
            s = "0" + s
        if len(e) == 1:
            e = "0" + e
        return s + "-" + e

"""
A function that takes the dougstats data and builds a pandas data frame
from it.
"""
def build_df(data):
    header = None
    lines = []
    for line in data.readlines():
        if not header:
            header = line.split() + ["YEAR"]
        else:
            stats = line.split()
            name = stats[0].split(",")
            try:
                stats[0] = str.upper(name[0] + ", " + name[1][0:3])
            except:
                stats[0] = str.upper(name[0])
            lines.append(stats + [year])
    return pd.DataFrame(lines, columns = header)

In [51]:
years = get_years()
season_dfs = [] # A list of data frames for each year

for year in years:
    url = "http://www.dougstats.com/{}RD.txt".format(year)
    data = urllib2.urlopen(url)
    season_dfs.append(build_df(data))

df = pd.concat(season_dfs) # Join all the data frames together

Filling years:
99-00
00-01
01-02
02-03
03-04
04-05
05-06
06-07
07-08
08-09
09-10
10-11
11-12
12-13
13-14
14-15
15-16
16-17

In [55]:
# Now we can take a look at our data and see what needs to be cleaned.
df

,+/-,3A,3M,AS,BK,DQ,EJ,FF,FGA,FGM,...,PS,PTS,Player,ST,Sta,TC,TO,TR,Team,YEAR
0,NaN,23,3,98,28,1,0,0,646,274,...,SG,697,"ABDUL-WAHAD, TAR",59,56,0,106,291,den,99-00
1,NaN,96,29,271,87,3,0,0,1277,594,...,SF,1663,"ABDUR-RAHIM, SHA",89,82,10,249,825,van,99-00
2,NaN,35,9,58,2,0,0,0,98,28,...,PG,82,"ALEXANDER, COR",24,2,0,28,42,den,99-00
3,NaN,407,172,308,19,1,0,0,1411,642,...,SG,1809,"ALLEN, RAY",110,82,2,183,359,mil,99-00
4,NaN,14,3,70,0,0,0,0,95,27,...,PG,60,"ALSTON, RAF",12,0,0,29,23,mil,99-00
5,NaN,6,1,95,37,1,0,0,700,306,...,C,836,"AMAECHI, JOH",35,53,0,139,266,orl,99-00
6,NaN,178,55,220,11,2,0,0,860,377,...,SG,1080,"ANDERSON, DER",90,58,0,167,258,lac,99-00
7,NaN,220,85,420,8,4,0,0,986,434,...,PG,1149,"ANDERSON, KEN",139,82,11,130,225,bos,99-00
8,NaN,397,132,123,16,0,0,0,782,306,...,SG,781,"ANDERSON, NIC",94,72,5,95,339,sac,99-00
9,NaN,225,79,239,32,0,0,0,778,368,...,SG,1009,"ANDERSON, SHA",96,82,0,194,384,hou,99-00
10,NaN,6,1,65,25,4,0,1,364,161,...,C,439,"ANSTEY, CHR",29,11,0,80,280,chi,99-00
11,NaN,233,88,208,9,0,0,1,416,169,...,PG,514,"ANTHONY, GRE",59,3,4,85,133,por,99-00
12,NaN,29,13,78,1,0,0,0,186,83,...,PG,201,"ARMSTRONG, B.J",7,18,0,40,47,chi,99-00
13,NaN,403,137,501,9,0,1,0,1119,484,...,PG,1330,"ARMSTRONG, DAR",169,82,5,248,270,orl,99-00
14,NaN,191,60,202,39,0,0,0,759,309,...,SF,866,"ARTEST, RON",119,63,0,166,308,chi,99-00
15,NaN,163,57,306,3,1,0,0,741,314,...,PG,782,"ATKINS, CHU",52,0,0,142,126,orl,99-00
16,NaN,2,0,53,11,0,0,1,175,83,...,SG,203,"AUGMON, STA",27,0,0,38,116,por,99-00
17,NaN,4,1,74,38,0,0,1,352,151,...,C,397,"AUSTIN, ISA",17,23,2,107,282,was,99-00
18,NaN,0,0,11,15,1,0,0,96,29,...,PF,81,"AVENT, ANT",16,3,0,24,74,lac,99-00
19,NaN,63,18,88,2,0,0,0,181,56,...,PG,154,"AVERY, WIL",14,1,0,42,40,min,99-00
20,NaN,10,2,30,4,0,0,0,140,58,...,SG,163,"BAILEY, TOB",13,2,0,24,72,pho,99-00
21,NaN,8,2,148,66,6,1,0,1129,514,...,PF,1311,"BAKER, VIN",47,75,7,213,605,sea,99-00
22,NaN,26,6,63,4,0,1,0,222,106,...,PF,289,"BARKLEY, CHA",14,18,2,44,209,hou,99-00
23,NaN,144,59,133,4,0,0,0,435,196,...,PG,517,"BARROS, DAN",31,0,0,66,99,bos,99-00
24,NaN,399,164,291,31,4,1,2,707,327,...,SG,945,"BARRY, BRE",103,74,4,142,372,sea,99-00
25,NaN,18,7,33,0,0,0,0,33,15,...,SG,41,"BARRY, DRE",2,0,0,13,12,atl,99-00
26,NaN,154,66,150,7,1,1,0,346,161,...,SF,495,"BARRY, JON",75,1,6,85,159,sac,99-00
27,NaN,8,1,63,70,4,0,2,459,219,...,PF,541,"BATTIE, TON",47,4,2,67,410,bos,99-00
28,NaN,12,2,3,5,0,0,0,70,23,...,PF,64,"BENDER, JON",1,1,0,7,21,ind,99-00
29,NaN,0,0,0,1,0,0,0,3,1,...,C,2,"BENJAMIN, BEN",0,0,0,0,1,cle,99-00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,122,228,95,190,8,0,0,0,613,286,...,PG,803,"WALKER, KEM",46,35,0,75,148,cha,16-17
418,33,113,37,319,18,0,0,0,586,273,...,PG,752,"WALL, JOH",74,32,8,142,144,was,16-17
419,-66,44,13,20,9,0,0,0,307,136,...,SF,334,"WARREN, T.J",33,16,1,23,91,pho,16-17
420,-19,37,11,39,0,0,0,0,77,22,...,PG,70,"WATSON, C.J",13,0,0,11,31,orl,16-17
421,84,3,2,73,18,0,0,0,113,63,...,PF,153,"WEST, DAV",22,0,2,40,97,gsw,16-17
422,174,206,65,378,11,0,0,0,863,366,...,PG,1114,"WESTBROOK, RUS",50,36,12,191,383,okl,16-17
423,-61,49,14,76,13,1,0,0,171,70,...,SG,180,"WHITEHEAD, ISA",18,19,0,59,61,bro,16-17
424,-82,0,0,23,77,1,0,0,452,247,...,C,588,"WHITESIDE, HAS",27,34,3,69,488,mia,16-17
425,-37,128,45,82,11,1,0,0,622,275,...,SF,761,"WIGGINS, AND",26,35,0,81,149,min,16-17
426,-7,12,2,9,1,0,0,0,17,5,...,SG,14,"WILCOX, C.J",1,0,0,4,9,orl,16-17
427,22,0,0,1,8,0,0,0,32,18,...,PF,45,"WILLIAMS, ALA",7,0,0,8,49,pho,16-17
428,-61,130,45,182,2,1,0,0,326,135,...,PG,374,"WILLIAMS, DER",17,27,0,66,62,dal,16-17
429,-19,39,8,10,4,0,0,0,121,50,...,PF,135,"WILLIAMS, DER",8,10,0,9,60,mia,16-17
430,50,190,70,119,7,0,0,0,482,211,...,SG,691,"WILLIAMS, LOU",48,0,1,81,86,lal,16-17
431,52,144,51,38,14,0,0,0,288,111,...,PF,305,"WILLIAMS, MAR",18,30,0,21,157,cha,16-17
432,-7,10,5,4,0,0,0,0,20,7,...,SF,25,"WILLIAMS, REG",3,0,0,0,6,nor,16-17
433,-64,41,10,19,9,0,0,0,122,51,...,SF,127,"WILLIAMS, TRO",25,13,0,27,44,mem,16-17
434,-24,10,3,0,1,0,0,0,10,3,...,??,10,"WILTJER, KYL",0,0,0,3,7,hou,16-17
435,-6,37,7,65,6,0,0,0,229,80,...,SF,196,"WINSLOW, JUS",27,15,1,33,94,mia,16-17
436,-23,1,0,2,19,0,0,0,41,23,...,C,62,"WITHEY, JEF",9,0,0,9,59,uta,16-17
437,-3,1,0,0,0,0,0,0,1,0,...,PF,0,"WOOD, CHR",0,0,0,0,2,cha,16-17
438,34,7,2,3,0,0,0,0,14,6,...,SG,14,"YOUNG, JAM",3,0,0,1,11,bos,16-17
439,-43,15,3,10,0,0,0,0,51,19,...,PG,49,"YOUNG, JOE",4,0,0,2,13,ind,16-17
440,-81,213,96,33,11,0,0,0,330,158,...,SF,459,"YOUNG, NIC",20,31,1,20,69,lal,16-17
441,4,88,37,56,14,1,0,0,348,183,...,PF,426,"YOUNG, THA",50,36,0,61,226,ind,16-17
442,162,0,0,45,34,0,0,0,220,131,...,C,333,"ZELLER, COD",21,29,0,34,191,cha,16-17
443,19,1,0,24,16,0,0,0,103,48,...,C,111,"ZELLER, TYL",5,5,0,10,79,bos,16-17
444,-9,0,0,1,1,0,0,0,11,5,...,??,10,"ZIMMERMAN, STE",1,0,0,0,14,orl,16-17
445,-8,4,0,4,0,0,0,0,13,1,...,SF,3,"ZIPSER, PAU",2,0,0,4,11,chi,16-17
446,-10,0,0,1,0,0,0,0,16,5,...,C,15,"ZUBAC, IVI",1,1,0,3,8,lal,16-17

In [52]:
from bs4 import BeautifulSoup

all_star_players = []

print "Scraping all star data from basketball.realgm.com"
for year in range(2000, 2017):
    url = "http://basketball.realgm.com/nba/allstar/game/rosters/{}".format(str(year))
    r = requests.get(url)
    data = r.text
    soup = BeautifulSoup(data, "lxml")
    tables = soup.find_all("table")
    print year

    for table in tables:
        rows = table.find_all('tr')[1:]
        for row in rows:
            cols = row.find_all('td')
            name = cols[0].get_text().split()
            name = name[1] + ", " + name[0][0:3]
            start = str((year - 1) % 100)
            end = str(year % 100)
            
            if len(start) == 1:
                start = "0" + start
            
            if len(end) == 1:
                end = "0" + end
                
            yr = start + "-" + end
            all_star_players.append([str.upper(str(name)), yr, 1])

print ""
all_star_players = pd.DataFrame(all_star_players, columns = ["Player", "YEAR", "AS?"])

Scraping all star data from basketball.realgm.com
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016

In [54]:
all_star_players

              Player   YEAR  AS?
0        BRYANT, KOB  99-00    1
1        DUNCAN, TIM  99-00    1
2       GARNETT, KEV  99-00    1
3          KIDD, JAS  99-00    1
4        O'NEAL, SHA  99-00    1
5        MALONE, KAR  99-00    1
6        FINLEY, MIC  99-00    1
7        PAYTON, GAR  99-00    1
8       WALLACE, RAS  99-00    1
9        WEBBER, CHR  99-00    1
10     ROBINSON, DAV  99-00    1
11     STOCKTON, JOH  99-00    1
12       CARTER, VIN  99-00    1
13      IVERSON, ALL  99-00    1
14     MOURNING, ALO  99-00    1
15        JONES, EDD  99-00    1
16         HILL, GRA  99-00    1
17        ALLEN, RAY  99-00    1
18     ROBINSON, GLE  99-00    1
19       MILLER, REG  99-00    1
20   STACKHOUSE, JER  99-00    1
21      MUTOMBO, DIK  99-00    1
22      HOUSTON, ALL  99-00    1
23        DAVIS, DAL  99-00    1
24      IVERSON, ALL  00-01    1
25      MCGRADY, TRA  00-01    1
26       CARTER, VIN  00-01    1
27     MOURNING, ALO  00-01    1
28         HILL, GRA  00-01    1
29        ALLEN, RAY  00-01    1
..               ...    ...  ...
409        PAUL, CHR  14-15    1
410     COUSINS, DEM  14-15    1
411     LILLARD, DAM  14-15    1
412    NOWITZKI, DIR  14-15    1
413       JAMES, LEB  15-16    1
414        WADE, DWY  15-16    1
415      GEORGE, PAU  15-16    1
416     ANTHONY, CAR  15-16    1
417       LOWRY, KYL  15-16    1
418      BUTLER, JIM  15-16    1
419     DEROZAN, DEM  15-16    1
420     MILLSAP, PAU  15-16    1
421    DRUMMOND, AND  15-16    1
422        BOSH, CHR  15-16    1
423        WALL, JOH  15-16    1
424      THOMAS, ISA  15-16    1
425       GASOL, PAU  15-16    1
426      HORFORD, AL  15-16    1
427      BRYANT, KOB  15-16    1
428      DURANT, KEV  15-16    1
429     LEONARD, KAW  15-16    1
430       CURRY, STE  15-16    1
431   WESTBROOK, RUS  15-16    1
432       GREEN, DRA  15-16    1
433      HARDEN, JAM  15-16    1
434        PAUL, CHR  15-16    1
435    THOMPSON, KLA  15-16    1
436       DAVIS, ANT  15-16    1
437     COUSINS, DEM  15-16    1
438    ALDRIDGE, LAM  15-16    1

[439 rows x 3 columns]

In [56]:
master_df = pd.merge(df, all_star_players, how='left', on=["Player", "YEAR"])

In [57]:
master_df.columns

Index([u'+/-', u'3A', u'3M', u'AS', u'BK', u'DQ', u'EJ', u'FF', u'FGA', u'FGM',
       u'FTA', u'FTM', u'GP', u'Min', u'OR', u'PF', u'PS', u'PTS', u'Player',
       u'ST', u'Sta', u'TC', u'TO', u'TR', u'Team', u'YEAR', u'AS?'],
      dtype='object')

In [58]:
team_dfs = []
print "Scraping team data from dougstats.com:"
for year in years:
    print year
    url = "http://www.dougstats.com/{}RD.Team.txt".format(year)
    data = urllib2.urlopen(url)
    team_dfs.append(build_df(data))

records_df = pd.concat(team_dfs) # Join all the data frames together

Scraping team data from dougstats.com:
99-00
00-01
01-02
02-03
03-04
04-05
05-06
06-07
07-08
08-09
09-10
10-11
11-12
12-13
13-14
14-15
15-16
16-17

In [59]:
records_df["Team"] = records_df["team"].map(lambda x: str.lower(x[0:3]))
records_df["win_pct"] = pd.to_numeric(pd.to_numeric(records_df["won"]) / 82.0)
records_df = records_df[["Team", "win_pct", "YEAR"]]
records_df

   Team   win_pct   YEAR
0   atl  0.341463  99-00
1   bos  0.426829  99-00
2   cha  0.597561  99-00
3   chi  0.207317  99-00
4   cle  0.390244  99-00
5   dal  0.487805  99-00
6   den  0.426829  99-00
7   det  0.512195  99-00
8   gsw  0.231707  99-00
9   hou  0.414634  99-00
10  ind  0.682927  99-00
11  lac  0.182927  99-00
12  lal  0.817073  99-00
13  mia  0.634146  99-00
14  mil  0.512195  99-00
15  min  0.609756  99-00
16  njn  0.378049  99-00
17  nyk  0.609756  99-00
18  orl  0.500000  99-00
19  phi  0.597561  99-00
20  pho  0.646341  99-00
21  por  0.719512  99-00
22  sac  0.536585  99-00
23  san  0.646341  99-00
24  sea  0.548780  99-00
25  tor  0.548780  99-00
26  uta  0.670732  99-00
27  van  0.268293  99-00
28  was  0.353659  99-00
0   atl  0.304878  00-01
..  ...       ...    ...
0   atl  0.231707  16-17
1   bos  0.256098  16-17
2   cha  0.243902  16-17
3   chi  0.219512  16-17
4   cle  0.317073  16-17
5   dal  0.134146  16-17
6   den  0.170732  16-17
7   det  0.195122  16-17
8   gsw  0.378049  16-17
9   hou  0.329268  16-17
10  ind  0.219512  16-17
11  lac  0.292683  16-17
12  lal  0.158537  16-17
13  mem  0.268293  16-17
14  mia  0.134146  16-17
15  mil  0.219512  16-17
16  min  0.134146  16-17
17  bro  0.097561  16-17
18  nor  0.170732  16-17
19  nyk  0.195122  16-17
20  orl  0.195122  16-17
21  phi  0.109756  16-17
22  pho  0.134146  16-17
23  por  0.182927  16-17
24  sac  0.182927  16-17
25  san  0.341463  16-17
26  okl  0.256098  16-17
27  tor  0.280488  16-17
28  uta  0.268293  16-17
29  was  0.195122  16-17

[535 rows x 3 columns]

In [60]:
master_df = pd.merge(master_df, records_df, how='left', on=["Team", "YEAR"])

In [61]:
master_df['AS?'] = master_df['AS?'].fillna(0)
del master_df['+/-']

In [62]:
good_columns = ['GP', '3A', '3M', 'AS', 'BK', 'FGA', 'FGM', 'FTM', 'FTA', 'OR', 'PF', 'PTS', 'ST', 'Sta', 'TO', 'TR']
master_df[good_columns] = master_df[good_columns].apply(pd.to_numeric)
good_columns.append('win_pct')

In [63]:
master_df['3A'] /= master_df['GP']
master_df['3M'] /= master_df['GP']
master_df['AS'] /= master_df['GP']
master_df['BK'] /= master_df['GP']
master_df['FGA'] /= master_df['GP']
master_df['FGM'] /= master_df['GP']
master_df['FTM'] /= master_df['GP']
master_df['FTA'] /= master_df['GP']
master_df['OR'] /= master_df['GP']
master_df['PF'] /= master_df['GP']
master_df['PTS'] /= master_df['GP']
master_df['ST'] /= master_df['GP']
master_df['Sta'] /= master_df['GP']
master_df['TO'] /= master_df['GP']
master_df['TR'] /= master_df['GP']

In [64]:
master_df['win_pct'] = np.nan_to_num(master_df['win_pct'])

In [65]:
target = "AS?"

In [66]:
from sklearn.cross_validation import train_test_split

In [68]:
old_data = master_df[master_df["YEAR"] != "16-17"]
new_data = master_df[master_df["YEAR"] == "16-17"]

train = old_data.sample(frac=0.8, random_state=1)
test = old_data.loc[~old_data.index.isin(train.index)]

In [69]:
print(train.shape)
print(test.shape)

(6204, 27)
(1551, 27)

In [70]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC

model = LinearRegression()
# Fit the model to the training data.
model.fit(train[good_columns], train[target])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [71]:
# Import the scikit-learn function to compute error.
from sklearn.metrics import mean_squared_error

# Generate our predictions for the test set.
predictions = model.predict(test[good_columns])

# Compute error between our test predictions and the actual values.
error = mean_squared_error(predictions, test[target])

print "ACCURACY: " + str(1 - error)

ACCURACY: 0.96835814773

In [76]:
new_data = new_data.reset_index()
arr = model.predict(new_data[good_columns])
top10 = arr.argsort()[-30:][::-1]

for i in top10:
    print new_data.ix[i]["Player"]

DAVIS, ANT
WESTBROOK, RUS
DURANT, KEV
HARDEN, JAM
JAMES, LEB
ANTETOKOUNMPO, GI
BUTLER, JIM
DEROZAN, DEM
THOMAS, ISA
COUSINS, DEM
LEONARD, KAW
LILLARD, DAM
HAYWARD, GOR
WALL, JOH
GRIFFIN, BLA
LOVE, KEV
GOBERT, RUD
GASOL, MAR
WALKER, KEM
IRVING, KYR
PAUL, CHR
CURRY, STE
LOWRY, KYL
WHITESIDE, HAS
HILL, GEO
WILLIAMS, LOU
JORDAN, DEA
CONLEY, MIK
TOWNS, KAR
GALLINARI, DAN

In [77]:
master_df.to_csv('player_data.csv')

In [78]:
new_data

,level_0,index,3A,3M,AS,BK,DQ,EJ,FF,FGA,...,Player,ST,Sta,TC,TO,TR,Team,YEAR,AS?,win_pct
0,0,7755,3.655172,1.310345,0.379310,0.103448,0,0,0,4.965517,...,"ABRINES, ALE",0.448276,0.000000,0,0.586207,1.172414,okl,16-17,0.0,0.256098
1,1,7756,1.333333,0.166667,0.000000,0.000000,0,0,0,2.833333,...,"ACY, QUI",0.000000,0.000000,0,0.333333,1.333333,dal,16-17,0.0,0.134146
2,2,7757,0.027778,0.000000,1.027778,0.944444,0,0,0,8.194444,...,"ADAMS, STE",1.250000,1.000000,2,1.916667,7.750000,okl,16-17,0.0,0.256098
3,3,7758,2.142857,0.785714,1.107143,0.035714,0,0,0,6.607143,...,"AFFLALO, ARR",0.285714,0.642857,0,0.500000,2.142857,sac,16-17,0.0,0.182927
4,4,7759,0.150000,0.000000,0.350000,0.700000,0,0,0,4.300000,...,"AJINCA, ALE",0.350000,0.500000,1,0.800000,4.500000,nor,16-17,0.0,0.170732
5,5,7760,0.000000,0.000000,0.516129,0.580645,1,0,0,1.935484,...,"ALDRICH, COL",0.612903,0.000000,0,0.225806,3.645161,min,16-17,0.0,0.134146
6,6,7761,0.781250,0.375000,2.093750,1.031250,0,0,0,13.812500,...,"ALDRIDGE, LAM",0.687500,1.000000,0,1.531250,7.250000,san,16-17,0.0,0.341463
7,7,7762,0.035714,0.000000,1.000000,0.285714,0,0,0,2.107143,...,"ALLEN, LAV",0.250000,0.000000,0,0.285714,2.500000,ind,16-17,0.0,0.219512
8,8,7763,0.612903,0.193548,1.032258,0.483871,0,0,0,8.580645,...,"ALLEN, TON",1.709677,0.935484,1,1.419355,5.419355,mem,16-17,0.0,0.268293
9,9,7764,3.526316,0.947368,2.157895,0.473684,1,0,0,6.842105,...,"AMINU, AL-",1.157895,0.842105,0,1.473684,6.157895,por,16-17,0.0,0.182927
10,10,7765,0.250000,0.000000,0.416667,0.583333,0,0,0,1.833333,...,"ANDERSEN, CHR",0.416667,0.000000,0,0.416667,2.583333,cle,16-17,0.0,0.317073
11,11,7766,1.500000,0.500000,0.428571,0.000000,0,0,0,2.928571,...,"ANDERSON, ALA",0.142857,0.000000,0,0.357143,1.071429,lac,16-17,0.0,0.292683
12,12,7767,2.696970,0.818182,0.696970,0.484848,0,0,0,6.515152,...,"ANDERSON, JUS",0.636364,0.060606,2,0.939394,3.636364,dal,16-17,0.0,0.134146
13,13,7768,0.482759,0.172414,1.034483,0.344828,0,0,0,2.344828,...,"ANDERSON, KYL",0.689655,0.310345,0,0.517241,2.965517,san,16-17,0.0,0.341463
14,14,7769,6.750000,2.777778,0.972222,0.305556,0,0,0,11.055556,...,"ANDERSON, RYA",0.444444,1.000000,0,0.944444,5.361111,hou,16-17,0.0,0.329268
15,15,7770,2.411765,0.705882,5.823529,1.941176,1,0,0,16.058824,...,"ANTETOKOUNMPO, GI",1.911765,1.000000,1,2.911765,9.117647,mil,16-17,0.0,0.219512
16,16,7771,5.676471,1.911765,2.941176,0.323529,0,0,0,18.558824,...,"ANTHONY, CAR",1.088235,1.000000,5,1.823529,6.205882,nyk,16-17,0.0,0.195122
17,17,7772,7.138889,2.694444,2.222222,0.305556,0,0,0,10.194444,...,"ARIZA, TRE",2.166667,1.000000,3,0.916667,5.194444,hou,16-17,0.0,0.329268
18,18,7773,0.923077,0.153846,0.307692,0.153846,0,0,0,1.615385,...,"ARTEST, RON",0.230769,0.076923,0,0.153846,0.538462,lal,16-17,0.0,0.158537
19,19,7774,2.200000,1.133333,1.000000,0.333333,0,0,0,4.133333,...,"ARTHUR, DAR",0.200000,0.200000,0,1.200000,1.866667,den,16-17,0.0,0.170732
20,20,7775,0.000000,0.000000,0.535714,0.428571,0,0,0,2.285714,...,"ASIK, OME",0.142857,0.642857,0,0.428571,5.714286,nor,16-17,0.0,0.170732
21,21,7776,3.918919,1.486486,3.108108,0.000000,0,0,0,7.081081,...,"AUGUSTIN, D.J",0.486486,0.540541,0,1.189189,1.351351,orl,16-17,0.0,0.195122
22,22,7777,2.758621,1.000000,0.413793,0.137931,0,0,0,4.310345,...,"BABBITT, LUK",0.310345,0.551724,0,0.344828,1.965517,mia,16-17,0.0,0.134146
23,23,7778,1.545455,0.363636,0.909091,0.090909,0,0,0,3.454545,...,"BAKER, RON",0.363636,0.000000,0,0.727273,1.090909,nyk,16-17,0.0,0.195122
24,24,7779,0.782609,0.086957,2.130435,0.260870,0,0,0,3.608696,...,"BALDWIN, WAD",0.565217,0.043478,0,1.347826,1.434783,mem,16-17,0.0,0.268293
25,25,7780,1.342857,0.600000,1.200000,0.085714,0,0,0,5.514286,...,"BARBOSA, LEA",0.514286,0.000000,0,0.428571,1.457143,pho,16-17,0.0,0.134146
26,26,7781,4.636364,1.727273,5.181818,0.090909,0,0,0,12.636364,...,"BAREA, J.J",0.727273,0.454545,1,1.727273,3.181818,dal,16-17,0.0,0.134146
27,27,7782,3.057143,1.028571,1.428571,0.228571,0,0,0,17.571429,...,"BARNES, HAR",0.857143,1.000000,0,1.400000,5.600000,dal,16-17,0.0,0.134146
28,28,7783,3.909091,1.303030,2.666667,0.363636,0,0,0,6.939394,...,"BARNES, MAT",0.666667,0.333333,4,1.636364,4.696970,sac,16-17,0.0,0.182927
29,29,7784,3.521739,1.347826,2.652174,0.434783,0,0,0,10.956522,...,"BARTON, WIL",0.826087,0.565217,0,1.652174,4.739130,den,16-17,0.0,0.170732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,417,8172,6.514286,2.714286,5.428571,0.228571,0,0,0,17.514286,...,"WALKER, KEM",1.314286,1.000000,0,2.142857,4.228571,cha,16-17,0.0,0.243902
418,418,8173,3.531250,1.156250,9.968750,0.562500,0,0,0,18.312500,...,"WALL, JOH",2.312500,1.000000,8,4.437500,4.500000,was,16-17,0.0,0.195122
419,419,8174,1.913043,0.565217,0.869565,0.391304,0,0,0,13.347826,...,"WARREN, T.J",1.434783,0.695652,1,1.000000,3.956522,pho,16-17,0.0,0.134146
420,420,8175,1.370370,0.407407,1.444444,0.000000,0,0,0,2.851852,...,"WATSON, C.J",0.481481,0.000000,0,0.407407,1.148148,orl,16-17,0.0,0.195122
421,421,8176,0.083333,0.055556,2.027778,0.500000,0,0,0,3.138889,...,"WEST, DAV",0.611111,0.000000,2,1.111111,2.694444,gsw,16-17,0.0,0.378049
422,422,8177,5.722222,1.805556,10.500000,0.305556,0,0,0,23.972222,...,"WESTBROOK, RUS",1.388889,1.000000,12,5.305556,10.638889,okl,16-17,0.0,0.256098
423,423,8178,1.884615,0.538462,2.923077,0.500000,1,0,0,6.576923,...,"WHITEHEAD, ISA",0.692308,0.730769,0,2.269231,2.346154,bro,16-17,0.0,0.097561
424,424,8179,0.000000,0.000000,0.676471,2.264706,1,0,0,13.294118,...,"WHITESIDE, HAS",0.794118,1.000000,3,2.029412,14.352941,mia,16-17,0.0,0.134146
425,425,8180,3.657143,1.285714,2.342857,0.314286,1,0,0,17.771429,...,"WIGGINS, AND",0.742857,1.000000,0,2.314286,4.257143,min,16-17,0.0,0.134146
426,426,8181,0.800000,0.133333,0.600000,0.066667,0,0,0,1.133333,...,"WILCOX, C.J",0.066667,0.000000,0,0.266667,0.600000,orl,16-17,0.0,0.195122
427,427,8182,0.000000,0.000000,0.071429,0.571429,0,0,0,2.285714,...,"WILLIAMS, ALA",0.500000,0.000000,0,0.571429,3.500000,pho,16-17,0.0,0.134146
428,428,8183,4.814815,1.666667,6.740741,0.074074,1,0,0,12.074074,...,"WILLIAMS, DER",0.629630,1.000000,0,2.444444,2.296296,dal,16-17,0.0,0.134146
429,429,8184,1.950000,0.400000,0.500000,0.200000,0,0,0,6.050000,...,"WILLIAMS, DER",0.400000,0.500000,0,0.450000,3.000000,mia,16-17,0.0,0.134146
430,430,8185,5.000000,1.842105,3.131579,0.184211,0,0,0,12.684211,...,"WILLIAMS, LOU",1.263158,0.000000,1,2.131579,2.263158,lal,16-17,0.0,0.158537
431,431,8186,4.800000,1.700000,1.266667,0.466667,0,0,0,9.600000,...,"WILLIAMS, MAR",0.600000,1.000000,0,0.700000,5.233333,cha,16-17,0.0,0.243902
432,432,8187,2.000000,1.000000,0.800000,0.000000,0,0,0,4.000000,...,"WILLIAMS, REG",0.600000,0.000000,0,0.000000,1.200000,nor,16-17,0.0,0.170732
433,433,8188,1.708333,0.416667,0.791667,0.375000,0,0,0,5.083333,...,"WILLIAMS, TRO",1.041667,0.541667,0,1.125000,1.833333,mem,16-17,0.0,0.268293
434,434,8189,1.111111,0.333333,0.000000,0.111111,0,0,0,1.111111,...,"WILTJER, KYL",0.000000,0.000000,0,0.333333,0.777778,hou,16-17,0.0,0.329268
435,435,8190,2.055556,0.388889,3.611111,0.333333,0,0,0,12.722222,...,"WINSLOW, JUS",1.500000,0.833333,1,1.833333,5.222222,mia,16-17,0.0,0.134146
436,436,8191,0.041667,0.000000,0.083333,0.791667,0,0,0,1.708333,...,"WITHEY, JEF",0.375000,0.000000,0,0.375000,2.458333,uta,16-17,0.0,0.268293
437,437,8192,1.000000,0.000000,0.000000,0.000000,0,0,0,1.000000,...,"WOOD, CHR",0.000000,0.000000,0,0.000000,2.000000,cha,16-17,0.0,0.243902
438,438,8193,0.636364,0.181818,0.272727,0.000000,0,0,0,1.272727,...,"YOUNG, JAM",0.272727,0.000000,0,0.090909,1.000000,bos,16-17,0.0,0.256098
439,439,8194,0.882353,0.176471,0.588235,0.000000,0,0,0,3.000000,...,"YOUNG, JOE",0.235294,0.000000,0,0.117647,0.764706,ind,16-17,0.0,0.219512
440,440,8195,6.870968,3.096774,1.064516,0.354839,0,0,0,10.645161,...,"YOUNG, NIC",0.645161,1.000000,1,0.645161,2.225806,lal,16-17,0.0,0.158537
441,441,8196,2.444444,1.027778,1.555556,0.388889,1,0,0,9.666667,...,"YOUNG, THA",1.388889,1.000000,0,1.694444,6.277778,ind,16-17,0.0,0.219512
442,442,8197,0.000000,0.000000,1.451613,1.096774,0,0,0,7.096774,...,"ZELLER, COD",0.677419,0.935484,0,1.096774,6.161290,cha,16-17,0.0,0.243902
443,443,8198,0.037037,0.000000,0.888889,0.592593,0,0,0,3.814815,...,"ZELLER, TYL",0.185185,0.185185,0,0.370370,2.925926,bos,16-17,0.0,0.256098
444,444,8199,0.000000,0.000000,0.125000,0.125000,0,0,0,1.375000,...,"ZIMMERMAN, STE",0.125000,0.000000,0,0.000000,1.750000,orl,16-17,0.0,0.195122
445,445,8200,0.444444,0.000000,0.444444,0.000000,0,0,0,1.444444,...,"ZIPSER, PAU",0.222222,0.000000,0,0.444444,1.222222,chi,16-17,0.0,0.219512
446,446,8201,0.000000,0.000000,0.142857,0.000000,0,0,0,2.285714,...,"ZUBAC, IVI",0.142857,0.142857,0,0.428571,1.142857,lal,16-17,0.0,0.158537

In [39]:
new_df.columns

Index([u'Player', u'Team', u'PS', u'GP', u'Min', u'FGM', u'FGA', u'3M', u'3A',
       u'FTM', u'FTA', u'OR', u'TR', u'AS', u'ST', u'TO', u'BK', u'PF', u'DQ',
       u'PTS', u'TC', u'EJ', u'FF', u'Sta', u'+/-', u'YEAR', u'team', u'won',
       u'lost', u'min', u'fgm', u'fga', u'3m', u'3a', u'ftm', u'fta', u'or',
       u'tr', u'as', u'st', u'to', u'bk', u'pf', u'pts', u'tc', u'ej', u'ff',
       u'win_pct'],
      dtype='object')